spring.application.name=fantasy-draft-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/fantasy_draft
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
